In [1]:
import scipy.stats as stats

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
dataset = sns.load_dataset('tips')

In [3]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Chi square test is performed to check the relation between two categorical features 
### in this example correlation between "sex" and "smoker"
### These categorical features need to be binary categories -- if more than two categories then use ANOVA test

In [5]:
dataset_table = pd.crosstab(dataset['sex'],dataset['smoker'])

In [6]:
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [8]:
observed_values = dataset_table.values

In [9]:
observed_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [10]:
val=stats.chi2_contingency(dataset_table)

In [11]:
val

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [12]:
Expected_Values=val[3]

In [13]:
Expected_Values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [14]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [16]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(observed_values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [17]:
chi_square

array([0.00119737, 0.00073745])

In [18]:
[i for i in zip(observed_values,Expected_Values)]

[(array([60, 97], dtype=int64), array([59.84016393, 97.15983607])),
 (array([33, 54], dtype=int64), array([33.15983607, 53.84016393]))]

In [19]:
chi_square_statistic

0.001934818536627623

In [20]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 0.001934818536627623


In [21]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [22]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.964915107315732
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.964915107315732


In [23]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Retain H0,There is no relationship between 2 categorical variables
Retain H0,There is no relationship between 2 categorical variables
