## Implementing Expectation Maximisation for a Gaussian Mixture

Notes:

Gaussian mixture - distribution with more than one normal distribution. A distribution with more than one peak- multi modal. Each normal distribution with its own mu and sigma values.

It can be used for both univariate and multivariate distributions

For theory --> https://www.youtube.com/watch?v=atDp5bkzej4

In [1]:
import silence_tensorflow
import tensorflow as tf
import tensorflow_probability as tfp

In [2]:
# !pip install silence_tensorflow

In [3]:
# !pip install tensorflow

In [4]:
# !pip install tensorflow_probability

In [5]:
pi_cluster = tf.constant([0.4,0.6])
mus = tf.constant([2.8,4.8])
sigmas = tf.constant([0.6,0.3])

In [6]:
cluster_distribution = tfp.distributions.Categorical(probs=pi_cluster,name="cluster")

In [7]:
cluster_distribution

<tfp.distributions.Categorical 'cluster' batch_shape=[] event_shape=[] dtype=int32>

In [8]:
cluster_distribution.sample()

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [9]:
cluster_distribution.sample(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 0, 1, 1, 0, 0, 0, 0, 1, 1])>

In [10]:
grade_distribution = tfp.distributions.Normal(loc=mus,scale=sigmas,name="grade")

In [11]:
grade_distribution

<tfp.distributions.Normal 'grade' batch_shape=[2] event_shape=[] dtype=float32>

In [12]:
grade_distribution.sample()

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.4927666, 4.760217 ], dtype=float32)>

In [13]:
grade_distribution.sample(10)

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[2.3230233, 5.182338 ],
       [3.7589855, 4.86073  ],
       [2.9347558, 4.769213 ],
       [2.5664532, 4.738344 ],
       [2.667532 , 4.5384636],
       [3.326954 , 4.819495 ],
       [2.7219644, 4.891525 ],
       [2.1888688, 4.271062 ],
       [2.4614687, 4.8959904],
       [2.4254892, 4.3613796]], dtype=float32)>

In [14]:
gaussian_mixture = tfp.distributions.MixtureSameFamily(mixture_distribution= cluster_distribution,components_distribution = grade_distribution)

In [15]:
gaussian_mixture

<tfp.distributions.MixtureSameFamily 'MixtureSameFamily' batch_shape=[] event_shape=[] dtype=float32>

In [16]:
gaussian_mixture.sample(10)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([4.728242 , 5.1969647, 4.739333 , 2.9790893, 4.7284255, 4.7696557,
       3.3009794, 3.2115507, 2.9165225, 3.2193136], dtype=float32)>

In [18]:
import numpy as np
import plotly.express as px

In [ ]:
# !pip install plotly

In [19]:
x = np.linspace(0.0,6.0,100)
y = gaussian_mixture.prob(x).numpy()

In [22]:
fig = px.line(x=x,y=y)

In [23]:
fig.show()